# app_key: "v4nfa8txxp8la8t"
# app_secret: "q0zo14rcm9m0ulg"
# access_token: "4xxszlbip1nskfxx"
# access_token_secret: "vv2e9yaxzjtlg20"
# user_id: "45373223"
# access_type: "app_folder"

app_key: "l8cre1vgu4vnvwr"
app_secret: "t95uan0p2tnuppn"
access_token: "wxgiv4pgiphssooz"
access_token_secret: "6kpzcxhp0svj04w"
user_id: "541167476"
access_type: "app_folder"